node {
  name = "smart-oilfield-emqx@127.0.0.1"
  cookie = "smart-oilfield-emqx-cookie"
  data_dir = "data"
  log_dir = "log"
}

cluster {
  name = "smart-oilfield-emqx-cluster"
  discovery_strategy = manual
}

listeners.tcp.default {
  bind = "0.0.0.0:1883"
  max_connections = 100000
  active_n = 100
  acceptors = 16
  proxy_protocol = false
  proxy_protocol_timeout = 3s
  backlog = 1024
  send_timeout = 15s
  send_timeout_close = true
  recbuf = 4KB
  sndbuf = 4KB
  buffer = 4KB
  tcp_keepalive = true
  tcp_keepalive_idle = 7200s
  tcp_keepalive_interval = 75s
  tcp_keepalive_probes = 9
  tcp_nodelay = true
}

mqtt {
  max_packet_size = 1MB
  max_clientid_len = 65535
  max_topic_levels = 65535
  max_qos_allowed = 2
  max_topic_alias = 65535
  retain_available = true
  wildcard_subscription = true
  shared_subscription = true
  strict_mode = false
  exclusive_subscription = false
  ignore_loop_deliver = false
  keepalive_backoff = 0.75
  keepalive_multiplier = 2
  session_expiry_interval = 2h
  max_inflight = 32
  reply_to_topic = false
  qos1_max_pending_msgs = 10000
  qos2_max_pending_msgs = 1000
  mqueue_priorities = []
  mqueue_default_priority = highest
  mqueue_store_qos0 = true
}

mqtt.force_gc_policy {
  count = 16000
  bytes = 16MB
}

mqtt.force_shutdown_policy {
  max_queue_len = 1000
  max_heap_size = 32MB
}

retainer {
  enable = true
  storage_type = built_in_database
  max_retained_messages = 100000
  max_payload_size = 1MB
}

authentication {
  authenticator1 {
    mechanism = password_based
    backend = built_in_database
    user_id_type = username
    password_hash_algorithm {
      name = sha256
      salt_position = suffix
    }
  }
}

authorization {
  deny_action = ignore
  no_match = allow
  cache {
    enable = true
    max_size = 1024
    ttl = 1m
  }
  sources = [
    {
      type = built_in_database
      enable = true
    }
  ]
}

limiter {
  bytes_in {
    rate = "infinity"
    capacity = 0
  }
  messages_in {
    rate = "infinity"
    capacity = 0
  }
  messages_out {
    rate = "infinity"
    capacity = 0
  }
}

log {
  file {
    default {
      enable = true
      level = warning
      file = "emqx.log"
      count = 10
      max_size = 50MB
      rotation = $size
    }
  }
}

dashboard {
  listeners.http {
    default {
      bind = 18083
    }
  }
  default_username = "admin"
  default_password = "public"
  i18n = en
}
